sudo: false
addons:
  apt:
    packages:
      - ghc
      - cabal-install
before_script:
  - "[[ ! -e $HOME/.cabal/bin/shellcheck ]] && cabal update && cabal install shellcheck"
cache:
  directories:
    - $HOME/.cabal
script:
  - PATH=${PATH}:$HOME/.cabal/bin bash lint.sh
