sudo: false
addons:
  apt:
    packages:
      - ghc
      - cabal-install
before_script:
  - cabal update
  - "[[ ! -e $HOME/cabal.bin ]] && cabal install shellcheck"
cache:
  - $HOME/.cabal
script:
  - PATH=${PATH}:$HOME/.cabal/bin bash lint.sh
