#!/bin/bash

# bash completion
function enable_bash_completion() {
    source_if_exists /etc/bash_completion
}

# Exports
export PATH=$PATH:/usr/local/bin # system local stuff
# user local stuff
if [[ -d $HOME/.local/bin ]]; then
    export PATH=$HOME/.local/bin:$PATH
fi

# some java programs rely on this to find the jre or jdk
if [[ -d /usr/lib/jvm/java-6-sun ]]; then
    export JAVA_HOME="/usr/lib/jvm/java-6-sun"
fi

# android sdk tools
if [[ -d $HOME/.local/lib/android-sdk-linux/tools ]]; then
    export PATH=$PATH:$HOME/.local/lib/android-sdk-linux/tools
fi
export XDG_DATA_HOME="$HOME/.local/share"
export OOO_FORCE_DESKTOP="gnome soffice"

# Aliases
alias ls='ls --color=auto' # add colors (gnu ls)
alias go='gnome-open' # try to open a file with an appropriate program
alias e="emacs -nw" # open emacs on the commandline
alias ex="emacs" # open an emacs window

