#!/bin/bash

# find homebrew cli to set up PATH etc
for prefix in '/opt/homebrew' '/usr/local'; do
    brew_cli="$prefix/bin/brew"
    if [[ -x "$brew_cli" ]]; then
        __eval_output_cached "$brew_cli" shellenv
        break
    fi
done

function enable_bash_completion() {
    if [[ -n "${BREW_PREFIX:-}" ]]; then
        source_if_exists "${BREW_PREFIX}/etc/bash_completion"
    elif command_is_defined brew
    then
        source_if_exists "$(brew --prefix)/etc/bash_completion"
    fi
}

export PATH="/usr/local/bin:$PATH:/usr/local/sbin"

# export LS_COLORS (Gnu/Linux) for readline, and set LSCOLORS (BSD) to match it (as closely as possible)
export LSCOLORS='exfxcxdxbxegedabagacad'
export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:or=35;7:su=31;7:sg=36;7:tw=32;7:ow=33;7:'

# Aliases
# use GNU ls if it is installed
if command_is_defined gls
then
    alias ls='gls --color=auto'
else
    alias ls='ls -G' # add colors (bsd ls)
fi
if command_is_defined ggrep # gnu grep > bsd grep
then
    alias grep='ggrep --color=auto'
else
    alias grep='grep --color=auto'
fi
alias emacs='emacs -nw' # don't start cocoa emacs by accident
alias ql='qlmanage -p 2> /dev/null &' # quicklook
alias dnslookup='dscacheutil -q host -a name'

if [[ -d '/Applications/Emacs.app' ]]
then
    function e() {
        if ! pgrep -qf 'Emacs.app'
        then
            for f in "${@}"; do
                if ! [[ -f "$f" ]]; then
                    touch "$f"
                fi
            done
            open -a '/Applications/Emacs.app' "$@"
        else
            emacsclient -n "$@"
        fi
    }
else
    alias e="emacs -nw"
fi
