#!/bin/bash

if [[ -x $(which brew) ]]
then
    # bash completion
    if [[ -f `brew --prefix`/etc/bash_completion ]]
    then
        . `brew --prefix`/etc/bash_completion
    fi

    # completion for the brew command
    if [ -f `brew --prefix`/Library/Contributions/brew_bash_completion.sh ]
    then
        . `brew --prefix`/Library/Contributions/brew_bash_completion.sh
    fi
fi

if [[ -e /usr/local/lib/node ]]
then
    export NODE_PATH=/usr/local/lib/node
fi

export PATH=/usr/local/bin:/usr/local/Cellar/python/2.7.1/bin:$PATH:/usr/local/sbin
launchctl setenv PATH $PATH
export PYMACS_PYTHON=/usr/local/bin/python2.7
if [[ -e $HOME/.cabal/bin ]]
then
    export PATH=$PATH:$HOME/.cabal/bin
fi

export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2.7
export JAVA_HOME=$(/usr/libexec/java_home)

# Aliases
alias emacs='emacs -nw' # don't start cocoa emacs by accident
alias ls='ls -G' # add colors (bsd ls)

# Functions
# open man page in Preview
function pman () {
    man -t "$@" | open -g -f -a /Applications/Preview.app
}
